package com.xypay.xypay.domain;

public enum UserRole {
    SUPERUSER,
    TELLER,
    CUSTOMER_SERVICE_OFFICER,
    LOAN_OFFICER,
    RELATIONSHIP_MANAGER,
    OPERATIONS_OFFICER,
    COMPLIANCE_OFFICER,
    TREASURY_OFFICER,
    IT_SUPPORT,
    BRANCH_MANAGER,
    OPERATIONS_MANAGER,
    CHIEF_RISK_OFFICER,
    EXECUTIVE
}
