# Customer Service HPA (Less traffic, smaller scaling)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: customer-service-hpa
  namespace: xypay-banking
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: customer-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

---
# Analytics Service HPA (CPU intensive, different thresholds)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: analytics-service-hpa
  namespace: xypay-banking
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: analytics-service
  minReplicas: 2
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60  # Scale earlier for CPU-intensive tasks
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70

---
# Treasury Service HPA (Critical service, always available)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: treasury-service-hpa
  namespace: xypay-banking
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: treasury-service
  minReplicas: 3  # Always keep 3 running for redundancy
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Scale early for critical service
